### ISSUE TITLE
腾讯课堂: ValueError: AES key must be either 16, 24, or 32 bytes long

### ISSUE THREAD

**Issue by StephanoGeorge** [yeefire/cloud-class-replay#2]
```
[18计算机最优化]——已下载第 647 个片段/ 共 672 个片段
[18计算机最优化]——视频全部下载完成
[18计算机最优化]——视频全部解密完成
Task exception was never retrieved
future: <Task finished name='Task-111602' coro=<decrypt_m3u8_video() done, defined at /home/cheese/Office/Codes/Projects/cloud-class-replay/tencent_class_m3u8.py:46> exception=ValueError('AES key must be either 16, 24, or 32 bytes long')>
Traceback (most recent call last):
File "/home/cheese/Office/Codes/Projects/cloud-class-replay/tencent_class_m3u8.py", line 52, in decrypt_m3u8_video
content_video_part = AES.new(key, AES.MODE_CBC, iv).decrypt(f)
File "/home/cheese/.local/lib/python3.9/site-packages/Crypto/Cipher/AES.py", line 95, in new
return AESCipher(key, *args, **kwargs)
File "/home/cheese/.local/lib/python3.9/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
File "/home/cheese/.local/lib/python3.9/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
self._cipher = factory.new(key, *args, **kwargs)
ValueError: AES key must be either 16, 24, or 32 bytes long
```

命令:

```shell
py3 tencent_class_m3u8.py 18计算机最优化 https://1258712167.vod2.myqcloud.com/fb8e6c92vodtranscq1258712167/3bbe741b5285890808047656849/drm/v.f30741.m3u8\?t\=601fd66e\&exper\=0\&us\=2480792150065044636\&sign\=fbadfce6944e086942045f47f2eac9ec
```

**Comment by yeefire** [comment]
请尝试找到正确的m3u8链接或手动在m3u8链接后拼接上请求token。现在应该是你选择的m3u8链接不正确导致请求m3u文件里的密钥请求链接没有携带token，脚本无法正确的获取解密密钥。

**Comment by yeefire** [comment]
通过你的链接拼接上token我已经成功的下载并解密你的视频资源。如有问题请访问博客寻找更多信息或与我联系。[Yee's Blog](https://blog.yeefire.com/2020_12/cloud_class_replay.html)

**Comment by StephanoGeorge** [comment]
请问 token 的键名是什么? APP(因为只有旧版APP能播放过期的回放)抓包得到的URL只有这些信息

我写的命令中的链接已经有如下参数:
```
t = 601fd66e
exper = 0
us = 9153162915156047384
sign = a245df106dd3adfbc938cc69e4ef9904
```

**Comment by StephanoGeorge** [comment]
APP的请求头是这样:
```
User-Agent: ARMMediaMetadataRetriever
Accept: */*
Range: bytes=0-
Connection: close
Host: 1258712167.vod2.myqcloud.com
Icy-MetaData: 1
```

刚发现即使此请求URL中不含 token, 响应体也会带有 token :
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://ke.qq.com/cgi-bin/qcloud/get_dk?edk=CiCL%2BJ216%2FA09EQGWCnDsmAx0u2HFATsa0oCXOv7QJp%2F6hCO08TAChiaoOvUBCokOTMyNDg4YmItOWZjYS00MzFiLWJiYjItNjFmMDhjYjNlYmM3&fileId=5285890808047656849&keySource=VodBuildInKMS&token=dWluPTE3Mjg4MDE5OTM7dGVybV9pZD0xMDI5NjIzNzc7cHNrZXk9M3FRSGc3bGxJOFdWT0xNOXAySkFlQjdkWC04aU1TSkQ1aXFvKkpUbmVuQV87ZXh0PQ",IV=0x00000000000000000000000000000000
#EXTINF:10.000000,
v.f30740.ts?start=0&end=109983&type=mpegts&sign=accb3b513851097fc5ca602db57cd545&t=601fd66e&us=9153162915156047384
```

**Comment by StephanoGeorge** [comment]
带上此 `token` 可以正常解密视频. 谢谢你
